### ISSUE TITLE
PDF24 not updated in the Chocolatey Repository

### ISSUE THREAD

**Issue by freaky-m0** [pocki/chocolateypackages#3]
Hi!

I see you have updated the source for PDF24 in your sources on github. But the changes are not published on the Chocolatey Repository. It's still a very old version 8.2.2 (https://chocolatey.org/packages/pdf24)

Is there any reason for that?

Thanks for your work!

**Comment by pocki** [comment]
Hi!
This is not an issue. I don't update to Chocolatey Repository anymore due the latest changes and policy. 
Feel free (you or someone else) to publish the package from this source to Chocolatey Repository. I can hand over the rights for this package on Chocolatey.

**Comment by freaky-m0** [comment]
That would be nice. How should we proceed?

**Comment by freaky-m0** [comment]
> 
> 
> Hi!
> This is not an issue. I don't update to Chocolatey Repository anymore due the latest changes and policy.
> Feel free (you or someone else) to publish the package from this source to Chocolatey Repository. I can hand over the rights for this package on Chocolatey.

How should we proceed?

**Comment by pocki** [comment]
Sorry for my late response.
I need your username at chocolatey.org because I have to add it to the package and to upload the new package. From this point on, you should be able to upload new versions. You can use the source of the package from this repository

**Comment by freaky-m0** [comment]
No problem. It's "freaky-m0" like here.

**Comment by pocki** [comment]
I have updated the package to the latest version (8.6.1) and uploaded to chocolatey. The automatic review process is running. I also added your username as package maintainer. Feel free to take the source from this repository and continue maintaining. Thanks!
